### ISSUE TITLE
headers not included

### ISSUE THREAD

**Issue by SmartManoj** [peace-maker/copy-as-python-requests#2]

**Comment by peace-maker** [comment]
Which headers? There's a default ignore list active which you can change in the settings. It only hides headers generated by the browser by default.

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/191155595-4678917e-3866-498f-96aa-16bd0e4132cb.png)
A quick button to disable ignore list would be better.
Also, an equivalent output like [curlconverter](https://curlconverter.com) would be nice.

**Comment by peace-maker** [comment]
I've added checkboxes to disable the ignore lists.

> Also, an equivalent output like [curlconverter](https://curlconverter.com/) would be nice.

Where the `params`, `headers`, and `cookies` are spread out into their own variables? That could get spammy quickly, but pretty neat as an option indeed.
