### ISSUE TITLE
Add post data

### ISSUE THREAD

**Issue by elya5** [peace-maker/copy-as-python-requests#4]
Hi,

It would be great if the data (and Content-Type) would be added for POST requests as well.

**Comment by peace-maker** [comment]
It should include the post data and content-type if non-standard already. Do you have an example site where the extension fails for me to look at?

**Comment by elya5** [comment]
You're right, I've now seen that it includes the POST data usually.  It didn't include it in the POST request [here on ieee](https://publication-recommender.ieee.org/pubsearch).

**Comment by peace-maker** [comment]
Thank you for the reproduction case. I've fixed it and published a new release. It's already live for firefox. Please report back if you encounter other problems.

**Comment by elya5** [comment]
Thanks for the quick fix!
