### ISSUE TITLE
invalid Python: `true` should be written `True`

### ISSUE THREAD

**Issue by monperrus** [peace-maker/copy-as-python-requests#5]
Great extension!

I copy a post request, with json as payload.
```
r = requests.post("https://lebowsky.com/graphql", json={"foo":true})
```
This is invalid Python,  `true` should be written `True`

Thanks!

**Comment by peace-maker** [comment]
Ah, right now I'm just pasting the request body verbatim as the json argument. Didn't think about bools. Maybe just wrapping the string in `json.loads`?

**Comment by monperrus** [comment]
that would work, but would be less elegant generated code.
